### ISSUE TITLE
Adding Columns to org

### ISSUE THREAD

**Issue by quequegg** [Discordanian/mmatch#10]
Needed columns:
SUBTYPE_DISCRIMINATOR - used to separate orgs seeking volunteers from other Movement Match clients.  
abbreviated name - many organizations use acronyms or other as an abbreviated name.  e.g. CAPCR 
BLURB_FOR_CUSTOMER - when Kurt "reveals" a match, this blurb is presented. It will importantly warn a customer away, as with ARC who works with whites to take ownership of their privilege, but also sell a customer on taking the next step.
VOLUNTEER_CONTACT_INSTRUCTIONS - When a customer selects an organization, these details are provided as the best way to contact the group.
BUSINESS_CONTACT_INSTRUCTIONS - This is for MM use to know how best to contact the organization.
(In the prior two attributes, I have intentionally kept it basic so that information like best time to call or best method to contact could provided without a lot of extra work on our part.)
ACTIVE_INDICATOR - We should have the ability to pause an organization for our purposes.  This would not be available to the organization.  (Occurs to me know that we could give the organization a pause button too... )

**Comment by alandgri** [comment]
Abbreviated_name added to DB and UI
org_type added to DB
customer_notice added to DB and UI
customer_contact added to DB and UI
admin_contacat added to DB and UI
active_ind added to DB and UI
admin_active_ind added to DB

**Comment by alandgri** [comment]
Shoot! The active indicator isn't coming across from the database. This works correctly on my local machine, so I am going to have to do some research.

**Comment by quequegg** [comment]
Very cool

**Comment by alandgri** [comment]
Fixed the active bug. I am closing this issue because the two remaining fields for which there is no UI are administrative functions, so they should be addressed by Issue #11

**Comment by quequegg** [comment]
My priority today is to help test
