### ISSUE TITLE
index.html / name of button

### ISSUE THREAD

**Issue by quequegg** [Discordanian/mmatch#103]
I wonder if when we click "start match" if we could change the text to "match lit" or change the initial text to "strike match" ... I love puns.

or, "List organizations in area and start filtering"

**Comment by alandgri** [comment]
Note that as we discussed a week or two ago, the default page is now index.php, not index.html. I did not implement an automatic forward from index.html to index.php, but that could be done.

**Comment by alandgri** [comment]
We discussed labeling this button "Next"

**Comment by quequegg** [comment]
Next is fine with me
