### ISSUE TITLE
Need to be able to add zip codes to organization

### ISSUE THREAD

**Issue by quequegg** [Discordanian/mmatch#12]
Organizations need to add 1:M zip codes.  The zip code would be a place where people could meet with the organization.

**Comment by alandgri** [comment]
Basic multiple zip functionality is there. Needs more filtering, more user feedback, maybe showing what the name of the city associated with the zip code.

**Comment by quequegg** [comment]
Fantastic.  I will be sure to dedicate time this weekend to this!

**Comment by alandgri** [comment]
I am closing this issue with my last commit (PR #25). Organizations can now add any (reasonable) number of zip codes to their record.
