### ISSUE TITLE
Cannot Reset Password

### ISSUE THREAD

**Issue by quequegg** [Discordanian/mmatch#120]
(Fails in Prod / Works in Dev; this may be just an issue of deploying code)
from https://stl.movementmatch.org/login.php?errmsg=SUCCESSFULLY_LOGGED_OFF
I enter my email que...  and password (ask me)
success.  Then I select the one org by clicking "edit"
I entered new password 12345 and verified as 12345 and click SAVE DATA
I get green bar with "Record Success... "
I click "Log Off" and get red bar with "Successfully logged ..."
I try to log in again with new password. Get red bar with "Those credentials are not valid..."
I log in with original password, success.  Password is not changed.
There is no update trigger on the table so there is nothing I can tell from looking at the db.

**Comment by alandgri** [comment]
yes, this is just an issue of not having the latest code. This was a side effect of the changes that I made for administrative functionality, is fixed in dev. I will sync up code in all environments today.

**Comment by alandgri** [comment]
All environments have been synchronized and password change code is functioning
