### ISSUE TITLE
User / Time Trigger on tables

### ISSUE THREAD

**Issue by quequegg** [Discordanian/mmatch#131]
We need to add the typical date and user trigger to files, at least the ones that are set up by organizations.

I need to be able to see if we are getting any traction from the organizations.

**Comment by alandgri** [comment]
I'd rather do this in the code than in triggers. One benefit is we can also track who made the changes.

**Comment by alandgri** [comment]
mysql actually has this functionality built into the timestamp data type. No trigger nor coding necessary. I will implement tonight.

**Comment by alandgri** [comment]
This is complete. I implemented in all environments for the org table. I will add it to the user table as well.

**Comment by quequegg** [comment]
Thanks!

**Comment by alandgri** [comment]
The special value '2000-01-01' for the update_timestamp is what will be seen for any rows that existed right now, but haven't been updated yet. Any new rows created after this will have the correct time stamp.
