### ISSUE TITLE
Organization Confirmation Page

### ISSUE THREAD

**Issue by quequegg** [Discordanian/mmatch#135]
Need to be able to echo back to organizations their selections. (relatively high priority)

I originally put together SQL to include app_user but decided it was simpler for the organization to put this at the organization level.  We would want a button next to the organization on the https://mmuat.movementmatch.org/orgList.php?user_id= page next to the Edit button. "Print" maybe.  I would rather not put it on the https://mmuat.movementmatch.org/org.php?orgid= unless we combined it with the save data.

I wrote the SQL to gather all the data together.  A couple of features:
- displays unselected choices
- decodes some status
- flattens out the org -> choices (I can unflatten if you like ... )
- does not include zip codes; use selectZipcodesForOrganization

My sketch of this report would look like this:
org data
---- choices
---- zip codes

Here is the SQL I wrote.  The asterisks are columns we do not currently use.

SELECT 	update_timestamp as "ACCOUNT AS OF",
		abbreviated_name AS "ABBR *",
		org_name AS "ORGANIZATION NAME",
		active_status AS "STATUS", 
		customer_contact AS "CONTACT FOR VOLUNTEER *",
		org_website AS "GENERAL WEB SITE",    
		money_url AS "WEB SITE FOR DONATIONS", 
		mission AS "MISSION", 
		customer_notice AS "MESSAGE TO VOLUNTEER *",
		admin_contact AS "NON PUBLIC CONTACT",
		/* NOTE: the use of this column is not known to me:         org.admin_active_ind, */
		/* An asterisk indicates that we are not currently using the information but could use it in the future*/ 
		/* Prior columns may repeat for each response below */  
		group_text AS "THEME",
		org_question_text AS "QUESTION",
		choice_text "CHOICE",
		CASE org_slct.selected 
			WHEN 1 
				THEN 'Selected'
			WHEN 0
				THEN 'NOT selected'
			ELSE 'New choice; added since your last review.'
			END AS "SELECTION STATUS" 
from
	(
		SELECT 
			org.orgid,
            qc.choice_id,
			qgr.page_num,           
			question.sort_order AS q_sort_order,
			qc.sort_order AS c_sort_order,
			org.update_timestamp,
            org.abbreviated_name,
			org.org_name,
			CASE org.active_ind WHEN 1
				THEN 'This organization is active.'
				ELSE 'INACTIVE'
				END AS active_status, 
			org.customer_contact,
			org.org_website,    
			org.money_url, 
			org.mission, 
			org.customer_notice,
			org.admin_contact,
			qgr.group_text,
			question.org_question_text,
			qc.choice_text 
			
		FROM org            

		JOIN question_choice AS qc
		/*	cartesian join*/
		INNER JOIN question
			ON (question.question_id = qc.question_id)
		INNER JOIN question_group qgr
			ON (qgr.group_id = question.question_group_id)
			
		WHERE orgid = 18
    ) all_choices
LEFT OUTER JOIN org_response AS org_slct
	ON (org_slct.org_id = all_choices.orgid AND
		org_slct.choice_id = all_choices.choice_id) 

ORDER BY all_choices.org_name, 
         CASE org_slct.selected 
			WHEN 1 
				THEN 2
			WHEN 0
				THEN 3
			ELSE 1
			END,
		 all_choices.page_num,           
         all_choices.q_sort_order,
         all_choices.c_sort_order

**Comment by alandgri** [comment]
Why choose between putting it on the list page? We can put it on both. I think this will be a separate page that will open in a new tab, so either way should work.

**Comment by quequegg** [comment]
We should execute a save if they hit the confirmation page

**Comment by alandgri** [comment]
True, I didn't think of that. thinking about how to do this where it's clean from the user perspective. Because if we have to do a save, then we also must kick off the validation, which means if validation fails, then the user could misinterpret what's happening (I just hit print, why is it saying my URL is invalid?) 

So initially can do it on the list page.

Maybe the way to put it on the org page is to not enable the print button if the record is dirty.

**Comment by quequegg** [comment]
I agree with your reasoning

**Comment by alandgri** [comment]
Report is in dev, as mentioned above, located on the list page next to the edit button

**Comment by alandgri** [comment]
What is out there is a draft, I welcome feedback

**Comment by quequegg** [comment]
This looks really good, I think this is a real step up.
Small points:
- It needs a key telling what the X, check, and grey means.
- Page 3/9 is consistently blank

I would like to get this into production as soon as we can.

**Comment by alandgri** [comment]
Report is in all environments. Looks good, except one issue which did not really present itself in other environments. The text length of some of the choices causes them to run into the other choices. I have a thought as to how to handle this, should probably have that out by tomorrow or so.

**Comment by alandgri** [comment]
This report is in all environments, with the fix mentioned above. It gets a tiny bit of overlap with really long choice descriptions, but it's definitely readable and I think this is a reasonable compromise.

**Comment by quequegg** [comment]
I am really happy to have this new feature.
