### ISSUE TITLE
When org.admin_active_ind = 0 then organization not showing in match

### ISSUE THREAD

**Issue by quequegg** [Discordanian/mmatch#140]
I toggled this 4 times to prove to myself this affect.  I cannot explain why the email from Amelia stated that they could see "Shoulders Down" when I was not able to see it.  When I toggled this flag I could make it appear and disappear.

Based on the name of this column, I feel like this is a bug.  If this is intended, we need to document this.  

I searched the stored procedures, I was not able to find mention of the column.  

In mmaz, I left org 55 (app_user.user_id = 40) as a test case.  Please delete these records when you are done with them.

**Comment by quequegg** [comment]
Related ... app_user.active_ind set to 0 does not prevent the organization from showing in the match.

**Comment by alandgri** [comment]
It's behaving as designed. The check is in selectNearbyOrgResponses:

`        WHERE org.active_ind = 1 AND org.admin_active_ind = 1`

The desired behavior is for an organization to be able to turn themselves on and off at will with active_ind. An administrator should be able to turn an org on and off at will with admin_active_ind. The two are independent, and an org is only shown if both are turned on, meaning the org and the admin agree that the org should be displayed.

App_user.active_ind = 0 disable the user from logging in but does not disable the org from displaying. This is behaving as designed.

**Comment by alandgri** [comment]
Also, I disabled shoulders down while I was logged on researching the password reset issue.

**Comment by quequegg** [comment]
Oh OK I got it. Embarrassing, I think that was something that I thought up.

Thanks for the refresher.
Bob
