### ISSUE TITLE
MINIMUM NUMBER OF CHOICES

### ISSUE THREAD

**Issue by quequegg** [Discordanian/mmatch#22]
I have gone back and forth between thinking have a question with a single choice is useful to thinking that a question with a single choice will look wrong to a customer.  

It may be that we will learn with use what we want to do.  I propose we have an integer on each question we can set such that if the value is 2 then we only allow a question if there are two choices or 1 if a question makes sense with a single choice.  

I added this column to both the old and new tables.

**Comment by alandgri** [comment]
There is a column named org_multi_select on the question table I modeled, which is used as a binary yes/no meaning is this multiple select for organizations. I can also add another column called customer_multi_select which has the same meaning only for customers.

**Comment by quequegg** [comment]
They are different, this new column intended to control the number of choices shown.  This is the case: of the organizations in the zip code, only one choice for a question remains.  E.g. There are 5 groups all looking for Spanish speakers and only Spanish speakers.  Would we have a question, "what languages can you work in?" If there was only Spanish as a choice?

**Comment by quequegg** [comment]
The column I added min_nbr_customer_choices. I have reconsidered and I am dropping it from my questionnaire template.  This should have no impact as I do not believe Kurt is looking at it.

My reasoning is that if Kurt eliminates choices that do not discriminate between organizations then this flag would be moot.
