### ISSUE TITLE
HOME PAGE FUNCTIONALITY

### ISSUE THREAD

**Issue by quequegg** [Discordanian/mmatch#23]
Alan and I talked about the home page at which the prospective volunteer (customer) will enter a zip code or die.

Please refer to the summer blockbuster at page 13.  
https://docs.google.com/presentation/d/1usH44SwVs3iA0rfDt7z1Cq3vf1Y8fcEnKeZOKu82AHU/edit#slide=id.g24a95a0514_1_84

The customer enters a zip code and a radius in miles and either:
a) is given a survey that will help her choose an organization (Kurt)
b) is simply given a couple of organizations in the area when # of organizations is less than MoveM.PARAMETERS.SHOW_ORGANIZATION_COUNT (or whatever you want to call it).
c) is redirected by invoking this page on a peer server passing the zip and radius as a parameter,
d) gets an error message

at a, Alan could pass:
1) Just a bag of organization keys
2) The entire query to display.  (See stored procs  ORG RESPONSE 4 CLIENT  and CUST SURVEY )

What do we want to do here?

**Comment by alandgri** [comment]
My first comment is that we should not kill the customer if they do not enter a zip code.

**Comment by alandgri** [comment]
I think it makes sense to return a JSON bundle of the entire list of nearby organizations and all their responses so that the front end can work its magic. No other filtering of orgs other than proximity. That way all matching logic is in the front end. All geography logic is in the back end.

**Comment by quequegg** [comment]
:) you are just no fun.

**Comment by quequegg** [comment]
I did not understand the last two sentences.
