### ISSUE TITLE
Choice Added After Organization Completes Registration

### ISSUE THREAD

**Issue by quequegg** [Discordanian/mmatch#24]
It is important to know the difference between an organization seeing but not selecting a choice and a choice added after the organization was set up that they never got a chance to select.  When setting up an organization's choices, create a row for every choice shown.  Mark those selected with a 1 and those not selected with a 0.  New choices will be null in this column.

A flag is provided on the question table which determines what should happen with that choice with no mark.  We can assume it was chosen or assume it was not chosen.  You can see this in the stored procedures such as CUST SURVEY.

**Comment by alandgri** [comment]
Is this a minimal viable product requirement? Doing this will require rewriting code that is already written and functioning.

**Comment by quequegg** [comment]
I suggest that a trigger on the table would take care of this.  Let me research

**Comment by alandgri** [comment]
This is complete via pull request #27 which has now been integrated into the master.
