### ISSUE TITLE
Org set up auto fill

### ISSUE THREAD

**Issue by quequegg** [Discordanian/mmatch#31]
I entered my own zip code, Chrome autofilled the Admin contact, name and email fields with my information. We should not autofill from individuals information.

**Comment by alandgri** [comment]
Autocomplete turned off by PR #35

**Comment by quequegg** [comment]
excellent thanks ... I am playing with adding questions and groups.  watch
out for differences.

**Comment by quequegg** [comment]
I added questions and choices from the data I had in my original tables.

I only have 7 questions that have choices ... I have 13 questions ... not
sure right now why only 7.  Too tired to start to track through.

I will drop these old tables soon,
