### ISSUE TITLE
Dreamhost Mysql is at v5.6

### ISSUE THREAD

**Issue by Discordanian** [Discordanian/mmatch#38]
This is an issue if we opt to store the DB on dreamhost.  I don't even currently see a plan to update any time soon but I might open a ticket there to see what their timeline is.

**Comment by alandgri** [comment]
This seems to be a non-issue at present, seems like our current hosting arrangement is working. Cautiously optimistic?

**Comment by Discordanian** [comment]
Closing.  Not relevant.
