### ISSUE TITLE
Users are able to create multiple organization records with the same user ID

### ISSUE THREAD

**Issue by alandgri** [Discordanian/mmatch#4]
Multiple records can be created with the same email address. This makes the action of authentication indeterminate, you will probably log onto the first one created and never be able to log into the subsequent records created. Maybe that's desired behavior, but the feedback to the user is inadequate.

**Comment by quequegg** [comment]
I cannot think of a good case where two organizations could not have different email addresses.

Should we encourage orgs to use something like info@website.com so that if there is a change in personnel they can manage it easier?

To keep it simple, if somebody loses control of an email account, can we expect them to contact Movement Match to get it straightened out?

**Comment by alandgri** [comment]
A couple of things that I was thinking about is one person is a board member for multiple organizations, and they want to use the same email address. Currently, we don't support this at all. Also we don't support one organization having multiple people with the ability to log in. I'd bet that will be a requirement in the future.

Another subtle concern is one person tries to create a record, either forget their password or forgets that they already succeeded. So they create another record with the same email address. Now behavior is indeterminate. They probably will not be able to log into the org that they last created. We need checks to prevent it from happening and messaging to inform the user. That's the thing that I think I should be working on.

**Comment by alandgri** [comment]
Yes, we can have maintenance screens for backend personnel to fix stuff. The login screen can detect what type of user they are and send them to the correct flow.

**Comment by quequegg** [comment]
I would like to help by putting together use cases for the scenarios you suggest.  

I would like to see zip code and the other dat a priority so that as others come behind you they can integrate their testing.

 Bob

**Comment by quequegg** [comment]
In the short term, I would like to put a unique index on email to ensure we do not frustrate a user ... for the site to crash is less frustrating that getting into a loop with the email addresses.

**Comment by quequegg** [comment]
In the short term, I would like to put a unique index on email to ensure we do not frustrate a user ... for the site to crash is less frustrating that getting into a loop with the email addresses.

**Comment by quequegg** [comment]
We need to investigate the index that is SUPPOSED to be enforcing unique email addresses.
