### ISSUE TITLE
Organization duplicated

### ISSUE THREAD

**Issue by quequegg** [Discordanian/mmatch#40]
I need to recreate this issue ... but we need to ensure that organization cannot be duplicated.  See Test Org 1 ... I think I entered that one time but it has been duplicated.

**Comment by quequegg** [comment]
Need to discuss.  I think you were raising a similar question a month ago

**Comment by alandgri** [comment]
There is now code to prevent duplicate organizations by organization name only. Other things like URL and abbreviation can be duplicated. Maybe URL should also be unique (if supplied)? Don't want to overengineer.

**Comment by Discordanian** [comment]
Is this issue closed?

**Comment by Discordanian** [comment]
Is this issue closed?
