### ISSUE TITLE
Organizations need to select multiple choices

### ISSUE THREAD

**Issue by quequegg** [Discordanian/mmatch#41]
Am I dreaming or did a prior version allow an organization to select more than one choice?

**Comment by alandgri** [comment]
Yes, it was and still is the case. However, all questions currently in the database marked as active also have org_multi_select = NULL, so it will not appear as if any questions allow multiple selections. Is it the intention for the field org_max_choices to represent this value? So it should display a multiple select box if org_max_choices is > 1?

**Comment by quequegg** [comment]
I think I see what is up.. talk later
