### ISSUE TITLE
The application javascript on the organization page does not work on Windows IE 8

### ISSUE THREAD

**Issue by alandgri** [Discordanian/mmatch#5]
IE 8 is no longer supported by Microsoft. It's a business decision as to whether we will support organizations using out of date software.

**Comment by alandgri** [comment]
Also doesn't work on IE 9.

**Comment by Discordanian** [comment]
I might be able to run it through a profiler to see what specifically I'm using that breaks IE9.

**Comment by Discordanian** [comment]
Do we need this issue open?  We aren't support IE 8/9, right?
