### ISSUE TITLE
Organization Update Time Out

### ISSUE THREAD

**Issue by quequegg** [Discordanian/mmatch#59]
Timed out while on Org Set Up, lost my work.  Is this necessary? (Why do we even have that lever Kronk?)

On Time out page, there is a submit button ... what is that intended to do?  Clicked it .. 

If we are to have a time out, can we make it a parameter on the parameters table.  (I prefer adding a column to a single row than to the more common way of having multiple rows with identifiers.)

**Comment by alandgri** [comment]
It was mostly a mistake, I accidentally left in the timeout set at 1 minute in 1 place that I had while I was testing. It is corrected now, set at 4 hours. Meaning that if you are working on the page for 4 hours without submitting it, it will kick you out. This is a security feature. This can obviously be changed but it's not a parameter that is tunable right now. It's in the code.
