### ISSUE TITLE
Need ability to reset password

### ISSUE THREAD

**Issue by quequegg** [Discordanian/mmatch#61]
As a priority, can I get a page that would allow me to enter an email and change a password?

**Comment by alandgri** [comment]
As an admin, change someone else's password, or change the password for the org/user that you are logging in as?

**Comment by quequegg** [comment]
as an admin ... in the case of a forgotten password.

**Comment by alandgri** [comment]
yeah, that's the admin functionality that I am working on which is getting a bit complicated. Not saying that it's not happening, but it's taking a while.

**Comment by alandgri** [comment]
Ability to reset password for both individuals and administrators is functioning in all environments

**Comment by quequegg** [comment]
Thank you!
