### ISSUE TITLE
When No Match on Zip

### ISSUE THREAD

**Issue by quequegg** [Discordanian/mmatch#63]
http://45.32.164.243/mmatch/match.php?zipcode=85001&distance=10

When there is no match, I get the "just show me" button (Missouri play on words?) but this is nonsensical because there is no match.

**Comment by Discordanian** [comment]
Did you also get a 'no records found'  alert?  From a user perspective, I can hide the 'show me' button.

**Comment by Discordanian** [comment]
'Show Me' button not visible when no records shown.
