### ISSUE TITLE
Delete unused columns

### ISSUE THREAD

**Issue by alandgri** [Discordanian/mmatch#78]
I am going to delete the unused columns like pwhash, emails, from org table.

**Comment by alandgri** [comment]
Implemented this in dev:

`mysql> alter table org drop column email_verified;
mysql> alter table org drop column email_unverified;
mysql> alter table org drop column person_name;
mysql> alter table org drop column pwhash;
`

**Comment by alandgri** [comment]
The unused user columns have been dropped from all databases.

**Comment by quequegg** [comment]
Thank you!  Much appreciated!
