### ISSUE TITLE
Zip code table maintenance

### ISSUE THREAD

**Issue by alandgri** [Discordanian/mmatch#82]
No reason to have multiple versions of the zip code table in different instances. So it should be separated into a different schema and then shared amongst all instances. Also, do we need an automatic routine to pull down new data, say monthly?

**Comment by alandgri** [comment]
Shared postal code table is loaded into a database called postcode. Although on second thought, maybe it should be more generically named so it can be shared for other types of data as well. Something to think about.

The dev application currently uses the shared zip code data.

**Comment by alandgri** [comment]
I convinced myself to rename the shared db to something like shared_db. Working on this and implementing in Dev environment now.

**Comment by alandgri** [comment]
This is in dev environment now with shared_db

**Comment by alandgri** [comment]
Closing this issue because both of these things are done. Zip codes are reloaded automatically from geonames.org source data on the first of every month. The zip code table postal_code_ref is in the shared_db database and referenced from every other schema.

**Comment by quequegg** [comment]
Great clean up! Thanks!
