### ISSUE TITLE
Synchronize database names with folder names

### ISSUE THREAD

**Issue by alandgri** [Discordanian/mmatch#83]
Just for the sake of consistency. 
This is the proposal:

- Rename /usr/share/httpd/html/mmatch to /usr/share/httpd/html/mmdev
- Rename MoveM database to mmdev 

- Rename MM_StL_UAT databse to mmuat

**Comment by quequegg** [comment]
I have read that renaming databases in MYSQL leads to issues.  So, just a heads up... if we start having weird issues we might need to recreate.

**Comment by alandgri** [comment]
Luckily it's only the "test" ones. It's not hard to recreate rather than rename. Just backup using mysqldump, drop database, then add back under new name. I'l wait a day or two before doing this.

**Comment by alandgri** [comment]
I implemented this. The old folders and old databases are still out there. I will delete those in due time.

**Comment by alandgri** [comment]
Closing this issue because there seem to be no problems as a result. Old databases have been dropped.
