### ISSUE TITLE
Customer Home Page Important, Easy Enhancements

### ISSUE THREAD

**Issue by quequegg** [Discordanian/mmatch#86]
1) Allow a local installation to show:

- Contact to volunteer
- Contact to have your organization added or modified

(Suggest: a installation parameter of a single text block.  Strings within text block that are recognized as URL or email made clickable when displayed.)

2) Size the data entry fields to be more suggestive of the intended content.  (i.e. why are they so damn big?)

3) Change "Zip Code" to "Find an organization active in this zip code" ... or suggest other language.  I am trying to use as few words as possible.

4) Change "Distance in Miles" to "Include organizations active within ... miles of this zip code."

5) Provide some kind of "About Movement Match" ... though I would prefer a drop down rather than a link to another page as I would not want to distract from just doing it. (Suggest: this be another installation parameter ... I would love this resource to be media rich with video and audio capabilities.  In my minds eye I see video montage of women's march, climate change march, Trump acceptance speech ...)

6) Okay ... and I wonder if when we click "start match" if we could change the text to "match lit" or change the initial text to "strike match" ... I love puns.

**Comment by Discordanian** [comment]
We need to keep these laundry list items split up.  There is no way to thread a cohesive discussion like this.  Can you split this up?
