### ISSUE TITLE
Customer Match Page Important Enhancements

### ISSUE THREAD

**Issue by quequegg** [Discordanian/mmatch#87]
@Discordanian 
(This issue highlights items in wiki https://github.com/Discordanian/mmatch/wiki/Backlog
The order here represents priority.)

1) Allow customer to select organization(s) and request contact. (_see notes at Wiki_) (_This is the biggest ask, but one we had always promised to provide.  Others listed here a much simpler_)

2) Randomize list of organization (fairness issue)

3) Display the donations website as well as the general website.
- Is it possible to default such that clicking a URL will open a new window so as to not take the user away from this page?

4) Change the name of the "Just Show Me" button to "Show Organizations"
- When displaying organizations, change the name of the button to "Hide Organizations"
- Display no more than (n) organizations at once.  (n is an installation parameter) Best if the random order from above is maintained for session to prevent a customer losing an organization that had been recommended.  This feature is intended to avoid overwhelming the customer and to make it harder to take the list for purposes we might not have intended.
- If limiting the number of matches, display "Showing n of N organizations in the area you selected."
- If limiting the number, or if showing more than (n) organizations, then show tips:
-- Select fewer choices within a single question (You might temper this by seeing if more than one choice is selected in any question.)
-- Make selections in more questions (You might condition this by seeing if any more questions are available to select.)
-- Return to zip code selection and reduce the number of miles to limit matches. (If number of miles is greater than zero.)

5) When only (n) organizations are found in a given zip code, show the organizations as is currently done but hide the questions.  (For faster performance, skip the query that constructs the questionnaire entirely.)

6) Ask customer to let us see their selections for our research. (_See Wiki for suggestions_)

7) As is suggested for customer home page, display text giving contact information.

8) Group questions
see: https://stl.movementmatch.org/org.php to see how Alan implemented
- Order groups according to sort order.
- Hide questions within group using +/- button

9) Tout the privacy protections somehow ... e.g. "About privacy" with a pop up.
- Note anonymity

10) Currently, at the bottom of the page we have: "Choices are not comprehensive. ..."
This is important information that I feel is buried.  
- **IMO We need to make these points**, I suggest a pop-up with a "got it" button to dismiss.
-- Choices are not comprehensive. If a selection a customer wants is not on the list it is not a slight, it just means no organization has that selection as a criteria. (Suggest: could be displayed if a drop down is engaged but no selection is made.)
- IMO the interface is sufficiently obvious such that we can down-play these next two:
-- All questions optional (skip all questions and get a random list)
-- Multi-select on most or all questions (see notes on phone conversation)

**Comment by Discordanian** [comment]
Closing this as it's a laundry list.  Breaking it out so it can be talked about in distinct threads.
