### ISSUE TITLE
Randomize org list (2)

### ISSUE THREAD

**Issue by Discordanian** [Discordanian/mmatch#89]
Randomize list of organization (fairness issue)

**Comment by quequegg** [comment]
Suggest we assign a random number to each organization as we pass it over from index.html to match.php.  match.php would have to altered to order by that new number.

**Comment by Discordanian** [comment]
Implementing Fischer Yates.

**Comment by quequegg** [comment]
tested 1-12-18 - everything is still alpha. I consider this a priority due to perceived fairness.

**Comment by Discordanian** [comment]
[master d8dfbb1] https://github.com/Discordanian/mmatch/issues/89
 1 files changed, 8 insertions(+), 0 deletions(-)
Counting objects: 7, done.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 515 bytes, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To git@github.com:Discordanian/mmatch.git
   d328e4c..d8dfbb1  master -> master
