### ISSUE TITLE
Display donations website + general (3)

### ISSUE THREAD

**Issue by Discordanian** [Discordanian/mmatch#90]
Display the donations website as well as the general website.

Is it possible to default such that clicking a URL will open a new window so as to not take the user away from this page?

**Comment by Discordanian** [comment]
I think I'm displaying every field I get.  Alan, is that not true?

**Comment by quequegg** [comment]
I looked at the stored procedure ... I find org.money_url - is it not in the JSON?

SELECT 
org.orgid, org.org_name, org.customer_notice, dist.distance, org_website, org.mission, 
	**org.money_url,** org.customer_contact, org.abbreviated_name,
	C.group_text, C.question_id, C.customer_question_text, C.choice_id, C.choice_text, 
	ORGR.org_response_id, 
    ORGR.selected AS selected

**Comment by alandgri** [comment]
money_url is indeed in the JSON

**Comment by quequegg** [comment]
In our meeting on 12/15 we discussed making better use of the space by putting the URLs on top of each other as:
Info: http://www.homepage.com (If not Null, please)
Donations: http://www.donationurl.com (if not NULL and not = to homepage)

We talked about not hiding the url to increase confidence that we were directing them properly.

**Comment by Discordanian** [comment]
ok.  I see it in the object but it's always empty.  Either way, if I get something, it gets displayed now.

**Comment by Discordanian** [comment]
Ok, AZ is always empty.  STL has some.  If they are there, they get displayed.

**Comment by quequegg** [comment]
Excellent!
