### ISSUE TITLE
Home Page contact info (7)

### ISSUE THREAD

**Issue by Discordanian** [Discordanian/mmatch#94]
As is suggested for customer home page, display text giving contact information.

**Comment by Discordanian** [comment]
Just tell me where you want it to point to or if we need a net-new page to point to.

**Comment by quequegg** [comment]
This was discussed on the conference call ... minutes on Nov 21.  I found this:
We decided to add to the opening page, https://az.movementmatch.org/index.html for example, a note or notes directing organizations or volunteers to the email for the person managing that region, eg Amelia.Lo.Social.Justice@gmail.com .  (Kurt, I did not get to voice my thought that we make this a repeating group of variable text and email in the configuration. ...)

I suggest:
"If you would like to help with MovementMatch, or if your organization would like to be listed, send an email to Amelia.Lo.Social.Justice@gmail.com"
and
"If you have a suggestion for how to improve this site, call Kurt Schwind at 314-266-8888"

**Comment by quequegg** [comment]
I think this is good.  I the text an installation parameter?  Please document at:
https://github.com/Discordanian/mmatch/wiki/Installation-Parameters

**Comment by alandgri** [comment]
Contact information popup has been deployed to all environments
