### ISSUE TITLE
Group Questions (8)

### ISSUE THREAD

**Issue by Discordanian** [Discordanian/mmatch#95]
Group questions
see: https://stl.movementmatch.org/org.php to see how Alan implemented

Order groups according to sort order.
Hide questions within group using +/- button

**Comment by Discordanian** [comment]
I hope we have fewer questions per match page, not more such that we need grouping.

**Comment by quequegg** [comment]
I suggest we postpone this as less essential.

**Comment by Discordanian** [comment]
I think I'm ripping the questions out of the data of the orgs.
```
[
   {
      "orgid":"18",
      "org_name":"Anti-Racist Collective",
      "distance":2.1,
      "customer_notice":"stlantiracismcollective@gmail.com",
      "mission":"blah blah.",
      "customer_contact":"",
      "abbreviated_name":"ARC",
      "org_website":"https:\/\/www.facebook.com\/ARCSTL\/",
      "money_url":"",
      "questions":[
         {
            "q_id":"39",
            "text":"I'd like to support organizations that work on:",
            "answers":[
               "Americans' mutual respect for people who look different (e.g. color of skin).",
               "Wealth distribution and economic systems."
            ]
         },
```
I'm calling function `getZipCodeData`

**Comment by quequegg** [comment]
My take on the number of questions is that there is a Goldilocks number between 3 and 12.  I want data from orgs to tune.  So for now we need to err on the high side.  We can kill questions at time of match.

**Comment by quequegg** [comment]
I have made very minor mods to selectNearbyOrgResponses. 
 Try this: Call`mmdev`.`selectNearbyOrgResponsesWIP`('63104', 50)
Group text was already there.  I added the columns on which you should sort.

From our meeting 0f 3/9, we added to this feature the ability to collapse all the filters.

**Comment by Discordanian** [comment]
orgs[0].questions[0];
Object { q_id: "28", text: "Which of the following issues do you most want to work on right now?", group_order: "10", answers: […] }

I've got a group order, but not a group order name.  Nor do I have a order for the questions so I'm sorting them by question id within each group.

But other than that, this is done and checked in.

**Comment by quequegg** [comment]
Dogone it... you have group text ... is that what you mean by group name?  And Alan should have added the question order... choice order too.

**Comment by Discordanian** [comment]
To git@github.com:Discordanian/mmatch.git
   2aa26bf..70cc2f8  master -> master

Done.  Thanks Alan for putting GroupText in there.
