### ISSUE TITLE
Privacy Information (9)

### ISSUE THREAD

**Issue by Discordanian** [Discordanian/mmatch#96]
Tout the privacy protections somehow ... e.g. "About privacy" with a pop up.
Note anonymity

**Comment by Discordanian** [comment]
Do we have the wording for the popup?  And do we want it on both the match and zip/dist screens?

**Comment by quequegg** [comment]
@Discordanian 
On the match page only,"
This page sends nothing out. Nothing on this page would cause your information to be seen by anyone but you unless they are standing behind you.  

On top of that, we ask nothing that would identify you; you are anonymous.
"
--- If you create the ability to save the information, we should mention that.
--- This could also be an installation parameter.

**Comment by alandgri** [comment]
Please review issues #94, #96, #100, #101, #102 in the dev environment. Particularly review the privacy policy wording, but also take a look at functionality and provide feedback in individual issues. If the functionality is ok, the footer can be added to other pages just by including it.

**Comment by quequegg** [comment]
cc Talia, Amelia
Re Privacy pop up at https://mmdev.metricsystem.tech/index.php

I like the privacy statement a lot.  I suggest this stripped down wording,
and I took out the promise until we have some paid staff or bots to oversee
things. see below:

This is our privacy policy. It's simple:

We do not collect personal identifying information, so you don't have to
trust us.

The questionnaire may feel like "Truth or Dare" but, none of your answers
on the questionnaire ever leave the browser.

What we do see: The zip code you enter; that is the first step in narrowing
the list of organizations. Also, every web site uses your IP address, that
is how the network knows where to send your information.

We do not have any trackers, ads, bugs, frames, or these types of things
that web sites use to unmask their users' identities.

That's it.

**Comment by alandgri** [comment]
Privacy popup has been deployed to all environments
