### ISSUE TITLE
index.html / size of data entry fields

### ISSUE THREAD

**Issue by quequegg** [Discordanian/mmatch#99]
Size the data entry fields to be more suggestive of the intended content. (i.e. why are they so damn big?)

**Comment by Discordanian** [comment]
Using default values from bootstrap.   This should be addressed when someone writes up some new CSS.  I can try and kludge something but I'm not sure if that'd break someone else's efforts when they apply their css.

**Comment by quequegg** [comment]
Size to be determined when graphics are done.

**Comment by Discordanian** [comment]
[master d328e4c] Issue 99
 1 files changed, 4 insertions(+), 4 deletions(-)
Counting objects: 5, done.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 334 bytes, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To git@github.com:Discordanian/mmatch.git
   c083357..d328e4c  master -> master
